import './js/switch-theme';
import './js/extra-block-slider';
import './js/modal-window';
import './js/burger-menu';
import './js/render-categories-list';
import './js/render-category-books';
import './js/books-action';
import './js/choose-category';
import './js/shopping-list';
import './js/firebase-app'
import './js/render-shopping-list'
